#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

fileList=$(git diff --staged --name-only :^package-lock.json :^.husky/pre-commit :^frontend :^backend)

echo '----- Checking Root...'

if [ ! -z "$fileList" ]
then
  echo "error: Unauthorized modifications\n"

  echo "$fileList\n"

  echo "use 'git restore --staged ...' to fix the problem"

  exit 1
fi

echo '----- Done!'


npm run lint